package enumeration;

/*
 * Author: Esteban Coto Alfaro
 * Creation Date: 16/09/2018
 * Last Modification: 17/09/2018
 * Description: Enum that define every type of token
 */
public enum Token 
{
	EQUALSOP, PLUSONEOP, LESSONEOP, GREATEROREQUALOP, LESSOREQUALOP, GREATEROP, LESSOP, DISTINCTOP, ASSIGNOP,
	ADDITIONOP, SUBTRACTIONOP, MULTIPLICATIONOP, DIVISIONOP, ID, INTEGERLIT, ERROR, RESERVEDWORDS, FLOATLIT,
	POINT, COMA, COLON, LEFTPAR, RIGHTPAR, LEFTSQU, RIGHTSQU, STRINGLIT, SEMICOLON;
}
