package enumeration;

public enum Token 
{
	EQUALSOP, PLUSONEOP, LESSONEOP, GREATEROREQUALOP, LESSOREQUALOP, GREATEROP, LESSOP, DISTINCTOP, ASSIGNOP,
	ADDITIONOP, SUBTRACTIONOP, MULTIPLICATIONOP, DIVISIONOP, ID, INTEGERLIT, ERROR, RESERVEDWORDS, FLOATLIT,
	POINT, COMA, COLON, LEFTPAR, RIGHTPAR, LEFTSQU, RIGHTSQU, STRINGLIT, SEMICOLON;
}
